application:
  version: 0.0.1
  title: Ums server
spring:
  application:
    name: ums
  jpa:
    open-in-view: false
  profiles:
    active:
      - dev
  sql:
    init:
      schemaLocations:
        - classpath:schema-sql/V1__reset-table.sql
        - classpath:schema-sql/V2__init-schema.sql
      dataLocations:
        - classpath:data-sql/V1_users.sql