spring:
  datasource:
    url: jdbc:mysql://mysql-server:3306/ums-build
    username: build-user
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      data-locations: db/schema.sql